### ISSUE TITLE
Adding Update Script to package.json

### ISSUE THREAD

**Issue by adrianmcli** [kadirahq/react-cdk#10]
Hey @arunoda, great work! I was thinking, since many people may not know yeoman very well and may not feel comfortable using it. Maybe it would help to put `yo react-cdk:update` inside package.json as an NPM script, so people could simply type:

```
npm run update
```

Thoughts?

**Comment by arunoda** [comment]
Hmm. I think that's too small for a NPM script.
Eventually, they'll get used to yo.
Since they've to use `yo react-cdk my-comp` when creating the component.

And we are planning to build a service which helps this process. See #7

**Comment by adrianmcli** [comment]
Sounds good!
