### ISSUE TITLE
yo react-cdk:update doesn't work for me

### ISSUE THREAD

**Issue by sakulstra** [kadirahq/react-cdk#12]
At first, thanks for this awesome tool ;)

When I try updating a react:cdk project via `yo react-cdk:update` I get an error like this:
$react-wizard: yo react-cdk:update

```
Error react-cdk:update 

You don't seem to have a generator with the name react-cdk:update installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 1 registered generators run yo with the `--help` option.
```

Regards,
Lukas

**Comment by arunoda** [comment]
Weird. Did you install generator-react-cdk globally?

**Comment by sakulstra** [comment]
Yes, I installed it globally - I even can use `yo react-cdk` to generate a new project. Just the:
`yo react-cdk:update` command doesn't work :/

Using Linux Mint 17.3 which should be based on latest ubuntu LTS and node v5.11 if this helps somehow.
Regards,
lukas

**Comment by arunoda** [comment]
Hey,

Yes we had a problem. Try updating `generator-react-cdk` globally and invoking: `yo react-cdk:update`. It should work now.

**Comment by sakulstra** [comment]
yep, seems to be fixed - thanks

**Comment by arunoda** [comment]
Cool.
