### ISSUE TITLE
Advice for using this in combination with Mantra modules?

### ISSUE THREAD

**Issue by zeroasterisk** [kadirahq/react-cdk#13]
Do you have advice for developing modules as stand-alone npm modules, but for use in a mantra (or Meteor imports dir structure) project?  

I know I could symlink to `src` while developing and then change paths, but I think there's a way to tell the parent app to use a npm module at a specific path...?  

If you have a development workflow you use for that sort of thing, I'd love to hear it.

thanks!
_(as usual, you continue to make awesome stuff, thanks!)_

**Comment by arunoda** [comment]
Frankly, I didn't yet moved any of mantra module to NPM. I didn't get a use case for that.
But, this we wrap some of the UI components which can be re-used and publish them into NPM.

We used CDK for them.

**Comment by usulpro** [comment]
@zeroasterisk can we close this?

if you feel you have something to add here, please reopen it!
