### ISSUE TITLE
Cannot resolve module 'webpack-hot-middleware/client'

### ISSUE THREAD

**Issue by zhangmengxue** [kadirahq/react-cdk#14]
I was just following the README...
when I  `npm run storybook` I got this error... Is there something wrong?

Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/yixuan/project/react-data-growth

**Comment by zhangmengxue** [comment]
While I install it through `npm install --save-dev webpack-hot-middleware` it worked...

Is it necessary to change the package.json?

I not sure but I think webpack-hot-middleware is the @kadira/storybook dependencies not the react-cdk itself. it gets this problem..
npm v2.14.20

**Comment by arunoda** [comment]
@zhangmengxue This is a known issue with React Storybook and you need to use NPM 3.
https://github.com/kadirahq/react-storybook/blob/master/docs/known_issues.md
