### ISSUE TITLE
`npm run storybook` fails

### ISSUE THREAD

**Issue by bartlomn** [kadirahq/react-cdk#16]
Running on osX / node v5.8.0.
Fresh from yo generation.
`npm install` runs OK, other scripts seem to be ok ok as well - including `npm run prepublish`
However running `npm run storybook` errors out with the following:

```
ERROR in ./src/stories/index.js
Module build failed: SyntaxError: /Users/Bart/Dev/Projects/Personal/react-comp-hello/src/stories/index.js: Unexpected token (7:4)
   5 | storiesOf('Button', module)
   6 |   .add('default view', () => (
>  7 |     <Button onClick={ action('button clicked') }>Hello</Button>
     |     ^
```

**Comment by dmitrika** [comment]
faced same problem with first run, lol

**Comment by usulpro** [comment]
@bartlomn @dmitrika do you still facing this error?

May I close it and redirect you to https://github.com/storybooks/react-storybook/issues/530 since it looks like more general node.js issue?

**Comment by bartlomn** [comment]
Please close, thanks.
