### ISSUE TITLE
Wrong Prop Types after publishing to Github pages

### ISSUE THREAD

**Issue by usulpro** [kadirahq/react-cdk#22]
I use `addWithInfo` to show prop types of the component

``` js
import SmTextarea from '../index';
...
.addWithInfo('Prop Types', () => {
    return ( <Something /> );
}, { propTables: [SmTextarea] })
```

It works well while development but after deploying to GitHub it reduced to one letter ([see here](https://sm-react.github.io/react-smart-textarea/?selectedKind=SmartTextarea&selectedStory=Prop%20Types&full=0&down=1&left=1&panelRight=0) **"t" Component**)
Looks like it minified for publishing but is there any way to show real name of a component?

**Comment by roonyh** [comment]
You can define a `displayName` for your components. See kadirahq/react-storybook-addon-info/issues/26

**Comment by usulpro** [comment]
thank you!

**Comment by roonyh** [comment]
You are welcome!
