### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by bestwestern** [kadirahq/react-cdk#24]
. ./.scripts/prepublish.sh 

is not recognized as an internal or external command (Windows 10)
[npm-debug.pdf](https://github.com/kadirahq/react-cdk/files/458964/npm-debug.pdf)

**Comment by usulpro** [comment]
@bestwestern, yes because it's shell script and you cant run it on windows. However, you can work with storybook nevertheless. This script you will need only to publish to npm (for translating to es5), but you can run same script for windows manually

**Comment by bestwestern** [comment]
Thank you very much for the quick reply!
May I recommend mentioning this in the Readme (that way you will not get these issues from newbie users like me ;-)

**Comment by usulpro** [comment]
you are welcome! :) 
I hope we will have full windows support sometime #6 
By the way, if you have [git](https://git-scm.com/download/win) installed on your system you can just start `Git Bash` from your project folder and type:
`$ bash`
`$ . ./.scripts/prepublish.sh`
