### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by jjstrat3** [kadirahq/react-cdk#28]
Hello,

I was wondering what the status was of the *react-cdk* and if there's plans for continuing development of new features and bug fixes?
I only ask because my team and I have been working to put together a set of UI components for the company I work for, and we have concerns to tying our development/publishing process to a tool such as this that may not be maintained.  In no way am I implying that your present/past efforts aren't appreciated, we just want know from the standpoint of ensuring we're using tools/technologies that will continue to receive support/updates.

Thanks for all your hard work!

**Comment by arunoda** [comment]
Yes. This is maintained.
We use this for almost every Storybook addon and some other projects.

**Comment by usulpro** [comment]
`React CDK` is now under the [storybooks](https://github.com/storybooks) org :sparkles:

I hope this will allow us to continue working on it with fresh strengths and ideas.
At this point, community participation and help can be particularly valuable!

**Comment by jjstrat3** [comment]
@UsulPro sounds good.  Hopefully time will allow me to help out here in the near future!  I'll go ahead and close this.
