### ISSUE TITLE
Delay in NPM install

### ISSUE THREAD

**Issue by MisterFantastic** [kadirahq/react-cdk#8]
I was noting some delay during "npm install" at this step.

node-pre-gyp install --fallback-to-build

It takes a while to move through this ES5 transpiring. Is this ok or some issue, please clarify ?

**Comment by arunoda** [comment]
It will take few seconds. If you don't have a SSD, it'll take more time.

**Comment by MisterFantastic** [comment]
thanks Arunoda. You can close this.

**Comment by arunoda** [comment]
Okay.
